language: node_js #Lenguaje a usar, este es JS
cache: 
 directories:
  - node_modules
  - ~/.npm
node_js: 
 - '12'
git:
  depth: 3
script:
  - yarn build

notifications:
email:
  reciepients:
  - jhonalexander9@gmail.com
  on_success: always
  on_failure: never
# manda emails a esos mails cuando es exitoso y cuando falla

deploy:
  provider: pages
  edge: true,
  cleanup: false
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  project_name: "MasterEats"
  target_branch: gh-pages
  commit_message: "Deploy Release from: %{git_branch} & with message: %{git_commit_msg}"
  verbose: true
  on:
    branch: master